name = "redminsights-crawler"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
SUPABASE_URL = "https://vimsbromshoerxcurbuz.supabase.co"

# SUPABASE_SERVICE_ROLE_KEY -> set via: wrangler secret put SUPABASE_SERVICE_ROLE_KEY

[triggers]
crons = ["0 * * * *"]
